
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: Windows-latest

steps:
- script: echo $MySECRET
  env:
    MySECRET: $(gh.token)
  displayName: 'Set env. variable'


- task: CmdLine@2
  displayName: Upload CodeQL results
  inputs:
      script: echo %TOKEN%
  env:
    TOKEN : $(gh.token)